# More stripping for low memory environments, removing e.g. RegExp support,
# coroutine support, etc.

DUK_USE_BUFFEROBJECT_SUPPORT: true

DUK_USE_REGEXP_SUPPORT: true

DUK_USE_REFERENCE_COUNTING: true
DUK_USE_STRHASH_DENSE: true
DUK_USE_TRACEBACKS: false
DUK_USE_PARANOID_ERRORS: true
DUK_USE_INTERRUPT_COUNTER: true
DUK_HTHREAD_INTCTR_DEFAULT: 1

# Consider to reduce code footprint at the expense of less safeguards against
# bugs in calling C code
DUK_USE_VALSTACK_UNSAFE: false

# Short term workaround with large footprint, disable.
DUK_USE_REGEXP_CANON_WORKAROUND: false

# Coroutine support has about 2kB footprint.
DUK_USE_COROUTINE_SUPPORT: false

# Finalizer support has about 0.8kB footprint.
DUK_USE_FINALIZER_SUPPORT: true

# ES2015 Proxy has about 2kB footprint.
DUK_USE_ES6_PROXY: false

# Don't support non-BMP characters in source code (UTF-8 otherwise OK).
DUK_USE_SOURCE_NONBMP: true

# Don't include even .name property for functions.
DUK_USE_FUNC_NAME_PROPERTY: false

# Remove built-in bindings.
DUK_USE_MATH_BUILTIN: true
DUK_USE_DATE_BUILTIN: false
DUK_USE_ARRAY_BUILTIN: true
DUK_USE_STRING_BUILTIN: true
DUK_USE_BOOLEAN_BUILTIN: true
DUK_USE_NUMBER_BUILTIN: true
DUK_USE_FUNCTION_BUILTIN: true
DUK_USE_OBJECT_BUILTIN: true
DUK_USE_DUKTAPE_BUILTIN: false
DUK_USE_JSON_BUILTIN: true
DUK_USE_ENCODING_BUILTINS: true
DUK_USE_REFLECT_BUILTIN: false
DUK_USE_JSON_SUPPORT: true
DUK_USE_CBOR_SUPPORT: false
DUK_USE_CBOR_BUILTIN: false
